api_platform:
    # The title of the API.
    title: "C'est un API de Voitures"
    # The description of the API.
    description: "Bla bla bla Description Api"
    # The version of the API.
    version: '1.1.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

